add fzf support

diff --git a/ktx b/ktx
--- a/ktx
+++ b/ktx
@@ -29,14 +29,23 @@ ktx() {
 
     # If no argument was given then list the files in $HOME/.kube
     if [ -z "$1" ]; then
-      for kube in $(find "${HOME}/.kube" -maxdepth 1 -type f -o -type l); do
-        if [[ "${KUBECONFIG}" == "$kube" ]]; then
-          echo -n "(active) "
+      if [[ -t 1 && "$(type fzf &>/dev/null; echo $?)" -eq 0 ]]; then
+        choice="$(FZF_DEFAULT_COMMAND='find "${HOME}/.kube" -maxdepth 1 -type f -o -type l | awk -F"/" "{print \$NF}"' fzf --ansi || true)"
+        if [[ -z "${choice}" ]]; then
+          echo 2>&1 "error: you did not choose any of the options"
+        else
+          export KUBECONFIG="${HOME}/.kube/${choice}"
         fi
-        echo $(basename "${kube}")
-      done
-
-      return
+        return
+      else
+        for kube in $(find "${HOME}/.kube" -maxdepth 1 -type f -o -type l); do
+          if [[ "${KUBECONFIG}" == "$kube" ]]; then
+            echo -n "(active) "
+          fi
+          echo $(basename "${kube}")
+        done
+        return
+      fi
     fi
 
     # If argument is "None" then unset the KUBECONFIG variable
